# Use an official RHEl with Python runtime as a base image
FROM ubi9/python-312

# Install system dependencies
RUN dnf update && \
    dnf install -y gcc unixodbc unixodbc-dev curl && \
    dnf clean

# Install Microsoft ODBC Driver for SQL Server
RUN dnf update && \
    dnf install -y gcc unixodbc unixodbc-dev curl gnupg && \
    dnf clean && \
    curl https://packages.microsoft.com/config/rhel/9/prod.repo | sudo tee /etc/yum.repos.d/mssql-release.repo

    yum remove unixODBC-utf16 unixODBC-utf16-devel #to avoid conflicts  
    ACCEPT_EULA=Y yum install -y msodbcsql17
    
    # optional: for bcp and sqlcmd
    ACCEPT_EULA=Y yum install -y mssql-tools
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
    source ~/.bashrc
    
    # optional: for unixODBC development headers
    yum install -y unixODBC-devel
    yum install -y mssql-server mssql-tools unixODBC-devel

# Create working directory
WORKDIR /app

# Copy current directory content to /app inside the container
COPY . /app

# Expose port 8000 for FastAPI
EXPOSE 8000

# Run the FastAPI server
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
