# apiVersion: v1
# kind: Pod
# metadata:
#     name: bus-project-pod
# spec:
#     containers:
#         - name: bus-project-producer
#           image: localhost/bus-project-producer # Local image reference

#         - name: bus-project-web
#           image: localhost/bus-project-web # Local image reference
#           ports:
#               - containerPort: 8000 # Expose port 8000 internally
#                 hostPort: 8000

apiVersion: v1
kind: Pod
metadata:
  name: bus-project-pod
spec:
  hostNetwork: true
  containers:
    - name: bus-project-producer
      image: localhost/bus-project-producer
      volumeMounts:
        - mountPath: /etc/pki/entitlement
          name: entitlement-volume
        - mountPath: /etc/rhsm
          name: rhsm-volume
        - mountPath: /etc/yum.repos.d
          name: yum-repos-volume

    - name: bus-project-web
      image: localhost/bus-project-web
      ports:
        - containerPort: 8000
          # hostPort: 8000
      volumeMounts:
        - mountPath: /etc/pki/entitlement
          name: entitlement-volume
        - mountPath: /etc/rhsm
          name: rhsm-volume
        - mountPath: /etc/yum.repos.d
          name: yum-repos-volume

    - name: kafdrop
      image: docker.io/obsidiandynamics/kafdrop:latest
      env:
        - name: KAFKA_BROKERCONNECT
          value: "localhost:9092" # Change this if your Kafka broker is using a different IP
      ports:
        - containerPort: 9000
          # hostPort: 9000 # Expose Kafdrop on port 9000

  volumes:
    - name: entitlement-volume
      hostPath:
        path: /etc/pki/entitlement
        type: Directory

    - name: rhsm-volume
      hostPath:
        path: /etc/rhsm
        type: Directory

    - name: yum-repos-volume
      hostPath:
        path: /etc/yum.repos.d
        type: Directory
