version: "3.8"
services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SA_PASSWORD: SomeStringPassword
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P SomeStringPassword -Q 'SELECT 1'",
        ]
      interval: 10s
      retries: 5
